// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSuBfED5e_KOvbflvSRvhdY65Q6-pCtng',
    appId: '1:83971057958:web:41e17e1a46b6f66a64f9e7',
    messagingSenderId: '83971057958',
    projectId: 'education-96b5d',
    authDomain: 'education-96b5d.firebaseapp.com',
    storageBucket: 'education-96b5d.appspot.com',
    measurementId: 'G-DQB72RHZ3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBBnT9v0D-CvvayIF4EPK6nblwlJzFmz0',
    appId: '1:83971057958:android:9e3e513dbb99267a64f9e7',
    messagingSenderId: '83971057958',
    projectId: 'education-96b5d',
    storageBucket: 'education-96b5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFFOw5WqvuxPElHk-AvOSuUm-F8xKZX6c',
    appId: '1:83971057958:ios:8c90b9b4f395236c64f9e7',
    messagingSenderId: '83971057958',
    projectId: 'education-96b5d',
    storageBucket: 'education-96b5d.appspot.com',
    iosClientId: '83971057958-clmsog91qnijomk2qliblh1db6je6oen.apps.googleusercontent.com',
    iosBundleId: 'com.example.education',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSuBfED5e_KOvbflvSRvhdY65Q6-pCtng',
    appId: '1:83971057958:web:1ffc1250500d98f664f9e7',
    messagingSenderId: '83971057958',
    projectId: 'education-96b5d',
    authDomain: 'education-96b5d.firebaseapp.com',
    storageBucket: 'education-96b5d.appspot.com',
    measurementId: 'G-MX9P2F6ZXL',
  );
}
